In [1]:
#Upload files from local system
from google.colab import files

uploaded = files.upload()

Saving ApexPlanet_DataAnalytics_Dataset.xlsx to ApexPlanet_DataAnalytics_Dataset.xlsx

In [2]:
#Reading Excel files using Pandas
import pandas as pd
df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")
df.info()
df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90
5,ORD100007,2025-12-31,CUST3952,Customer_71,40.0,Female,Hyderabad,Laptop,Electronics,9,35947.47,323527.23
6,ORD100008,2025-10-14,CUST1758,Customer_335,61.0,Male,Patna,Mobile,Electronics,6,49997.53,299985.18
7,ORD100009,2025-12-05,CUST9622,Customer_224,35.0,Male,Kolkata,Laptop,Electronics,3,9488.83,28466.49
8,ORD100010,2025-11-21,CUST9770,Customer_494,41.0,Female,Mumbai,Book,Education,6,19488.23,116929.38
9,ORD100011,2025-04-16,CUST1312,Customer_40,30.0,Male,Kolkata,Mobile,Electronics,8,18024.34,144194.72
10,ORD100012,2025-05-05,CUST9642,Customer_162,51.0,Male,Delhi,Shoes,Fashion,3,14151.42,42454.26
11,ORD100013,2025-05-02,CUST3228,Customer_209,55.0,Female,Patna,Chair,Furniture,6,47175.43,283052.58
12,ORD100014,2025-05-06,CUST1038,Customer_454,32.0,Male,Patna,Rice,Grocery,5,7413.68,37068.40
13,ORD100015,2025-04-24,CUST6413,Customer_490,50.0,Female,Patna,Shoes,Fashion,8,12042.52,96340.16
14,ORD100016,2025-03-12,CUST8660,Customer_213,42.0,Female,Patna,Mobile,Electronics,8,25465.31,203722.48
15,ORD100017,2025-08-30,CUST9307,Customer_313,36.0,Female,Delhi,Shoes,Fashion,10,20111.09,201110.90
16,ORD100018,2025-11-30,CUST4363,Customer_161,30.0,Female,Delhi,Book,Education,10,40109.12,401091.20
17,ORD100019,2025-10-19,CUST3508,Customer_67,31.0,Male,Gaya,Shoes,Fashion,1,7280.64,7280.64
18,ORD100020,2025-07-24,CUST5806,Customer_103,57.0,Female,Mumbai,Chair,Furniture,5,6122.59,30612.95
19,ORD100021,2025-03-20,CUST6504,Customer_357,34.0,Male,Kolkata,Laptop,Electronics,8,23770.36,190162.88

In [3]:
#statistical data
df.describe(include='all')

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
count,1000,1000,1000,1000,980.000000,1000,987,1000,1000,1000.000000,1000.000000,1000.000000
unique,992,342,947,425,NaN,2,8,6,5,NaN,NaN,NaN
top,ORD100050,2025-04-16,CUST2515,Customer_359,NaN,Male,Patna,Mobile,Electronics,NaN,NaN,NaN
freq,9,10,3,8,NaN,511,135,184,354,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,41.360204,NaN,NaN,NaN,NaN,5.435000,25486.783410,139399.439650
std,NaN,NaN,NaN,NaN,13.822597,NaN,NaN,NaN,NaN,2.838632,14179.402361,114100.051546
min,NaN,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,1.000000,145.780000,437.340000
25%,NaN,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,3.000000,13895.722500,47066.632500
50%,NaN,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,5.000000,25398.740000,108594.025000
75%,NaN,NaN,NaN,NaN,54.000000,NaN,NaN,NaN,NaN,8.000000,37512.382500,203722.882500
max,NaN,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,10.000000,49997.530000,493677.500000

In [4]:
#checking null values in each column
print(df.isnull().sum())

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [7]:
#Filling null values using mean,mode,median
df['Age']=df['Age'].fillna(df['Age'].mean())
df['City']=df['City'].fillna(df['City'].mode()[0])

In [8]:
#verifying null value exists or not
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

In [9]:
#Checking the duplicated records
df.duplicated().sum()

np.int64(0)

In [10]:
#Removing duplicate records
df=df.drop_duplicates()

In [11]:
#verifying the records
df.duplicated().sum()

np.int64(0)

In [12]:
#Outlier Detection
Q1=df['Total_Sales'].quantile(0.25)
Q3=df['Total_Sales'].quantile(0.75)
IQR=Q3-Q1
lower_fence=Q1-1.5*IQR
upper_fence=Q3+1.5*IQR
print(lower_fence)
print(upper_fence)

-187917.7425
438707.2575

In [13]:
#filter the data
filter_data=df[df['Total_Sales'].between(lower_fence,upper_fence)]
print(filter_data)

      Order_ID  Order_Date Customer_ID Customer_Name        Age  Gender  \
0    ORD100002  2025-02-25    CUST5529  Customer_227  30.000000  Female
1    ORD100003  2025-10-14    CUST3127  Customer_182  63.000000    Male
2    ORD100004  2025-05-13    CUST8887  Customer_487  62.000000  Female
3    ORD100005  2025-12-02    CUST2515  Customer_470  65.000000  Female
4    ORD100006  2025-11-20    CUST4796  Customer_380  44.000000    Male
..         ...         ...         ...           ...        ...     ...
995  ORD100997  2025-11-07    CUST6410  Customer_301  61.000000    Male
996  ORD100998  2025-09-03    CUST7618  Customer_154  25.000000    Male
997  ORD100999  2025-09-30    CUST9544  Customer_140  62.000000  Female
998  ORD101000  2025-02-21    CUST9501  Customer_241  41.360204    Male
999  ORD101001  2025-04-23    CUST2714   Customer_98  58.000000  Female

          City Product     Category  Quantity  Unit_Price  Total_Sales
0    Bengaluru    Rice      Grocery         7     2829.77     19808.39
1    Bengaluru    Book    Education         5    27906.16    139530.80
2    Bengaluru    Book    Education         8    37491.06    299928.48
3      Kolkata  Mobile  Electronics         9    28541.36    256872.24
4    Bengaluru    Rice      Grocery        10    14036.59    140365.90
..         ...     ...          ...       ...         ...          ...
995       Gaya  Laptop  Electronics         9    35405.54    318649.86
996       Gaya   Shoes      Fashion         5    18454.65     92273.25
997  Hyderabad  Laptop  Electronics         9    12971.59    116744.31
998      Delhi  Mobile  Electronics         9     2879.01     25911.09
999       Gaya   Chair    Furniture         9    22493.87    202444.83

[981 rows x 12 columns]

In [14]:
df.to_excel("ApexPlanet_DataAnalytics_Dataset.xlsx", index=False)

In [15]:
#Cleaned Dataset gets downladed
from google.colab import files

files.download("ApexPlanet_DataAnalytics_Dataset.xlsx")

In [16]:
!ls
#clenaed dataset

ApexPlanet_DataAnalytics_Dataset.xlsx  sample_data