In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Sales_Dataset_With_Missing_And_Duplicates.xlsx to Sales_Dataset_With_Missing_And_Duplicates.xlsx

In [ ]:
import pandas as pd
df = pd.read_excel("Sales_Dataset_With_Missing_And_Duplicates.xlsx")
df.info()
df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       95 non-null     object
 1   Customer Name  94 non-null     object
 2   Product        94 non-null     object
 3   Sales          93 non-null     float64
 4   Profit         94 non-null     float64
 5   Order Date     94 non-null     object
dtypes: float64(2), object(4)
memory usage: 4.6+ KB

   Order ID Customer Name     Product     Sales    Profit  Order Date
0   ORD1001        Vikram       Mouse   6115.73    587.73  2025-05-13
1   ORD1002         Rohit         SSD  33108.03   8954.31  2025-07-04
2   ORD1003        Anjali      Laptop  48616.51  13753.05  2025-04-10
3   ORD1004         Sneha       Mouse   9359.93   1682.14  2025-11-17
4   ORD1005         Aarav      Webcam  46666.22   4938.17  2025-10-04
5   ORD1006         Aarav       Mouse  30337.58   3953.19  2025-04-05
6   ORD1007         Meera       Mouse  47162.16   9739.25  2025-08-31
7   ORD1008        Vikram      Webcam  18919.03   5084.18  2025-06-08
8   ORD1009         Kiran  Headphones  30639.70   1627.59  2025-12-28
9   ORD1010         Kiran      Laptop  41718.68   6022.98  2025-01-26
10  ORD1011         Rohit      Webcam  23283.10   4626.92  2025-11-30
11  ORD1012        Vikram     Printer  24485.08   3402.81  2025-05-26
12  ORD1013         Pooja     Printer  26442.75   2318.62  2025-11-12
13  ORD1014           NaN      Laptop  35725.55   9632.22  2025-11-12
14  ORD1015         Meera         SSD  25917.46   1652.19  2025-02-08
15  ORD1016         Rahul         SSD  12068.88   3052.48  2025-04-18
16  ORD1017        Vikram       Mouse  38122.72   9079.86  2025-12-16
17  ORD1018        Vikram      Webcam  21799.85   4603.47  2025-12-26
18  ORD1019         Rohit      Webcam  19741.20   4966.19  2025-08-17
19  ORD1020         Sneha      Laptop  36025.01  10605.03  2025-02-03

In [ ]:
df.describe(include='all')

       Order ID Customer Name Product         Sales        Profit  Order Date
count        95            94      94     93.000000     94.000000          94
unique       90            10       8           NaN           NaN          75
top     ORD1041         Rohit  Webcam           NaN           NaN  2025-12-26
freq          3            13      19           NaN           NaN           4
mean        NaN           NaN     NaN  27267.360538   5234.209681         NaN
std         NaN           NaN     NaN  12900.150814   3420.270156         NaN
min         NaN           NaN     NaN   1910.920000    205.590000         NaN
25%         NaN           NaN     NaN  16470.250000   2458.622500         NaN
50%         NaN           NaN     NaN  27113.000000   4603.730000         NaN
75%         NaN           NaN     NaN  38122.720000   7519.195000         NaN
max         NaN           NaN     NaN  49029.000000  13753.050000         NaN

In [ ]:
print(df.isnull().sum())

Order ID         0
Customer Name    1
Product          1
Sales            2
Profit           1
Order Date       1
dtype: int64

In [ ]:

df['Customer Name']=df['Customer Name'].fillna(df['Customer Name'].mode()[0])
df['Product']=df['Product'].fillna(df['Product'].mode()[0])
df['Sales']=df['Sales'].fillna(df['Sales'].mean())
df['Profit']=df['Profit'].fillna(df['Profit'].median())
df['Order Date']=df['Order Date'].fillna(df['Order Date'].mode()[0])

In [ ]:
df.isnull().sum()

Order ID         0
Customer Name    0
Product          0
Sales            0
Profit           0
Order Date       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(5)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
Q1=df['Sales'].quantile(0.25)
Q3=df['Sales'].quantile(0.75)
IQR=Q3-Q1
lower_fence=Q1-1.5*IQR
upper_fence=Q3+1.5*IQR
print(lower_fence)
print(upper_fence)

-15171.028749999994
70046.04125

In [ ]:
filter_data=df[df['Sales'].between(lower_fence,upper_fence)]
print(filter_data)

   Order ID Customer Name     Product     Sales    Profit  Order Date
0   ORD1001        Vikram       Mouse   6115.73    587.73  2025-05-13
1   ORD1002         Rohit         SSD  33108.03   8954.31  2025-07-04
2   ORD1003        Anjali      Laptop  48616.51  13753.05  2025-04-10
3   ORD1004         Sneha       Mouse   9359.93   1682.14  2025-11-17
4   ORD1005         Aarav      Webcam  46666.22   4938.17  2025-10-04
..      ...           ...         ...       ...       ...         ...
85  ORD1086         Rohit       Mouse  33079.40   7135.27  2025-03-10
86  ORD1087         Sneha       Mouse  19796.46   2062.45  2025-10-26
87  ORD1088         Kiran      Webcam  48640.43  10761.81  2025-01-23
88  ORD1089         Priya  Headphones  16470.25   1247.80  2025-04-25
89  ORD1090         Pooja         SSD  27113.00   1908.07  2025-12-18

[90 rows x 6 columns]

In [ ]:
df.to_excel("Sales_Dataset_With_Missing_And_Duplicates.xlsx", index=False)

In [ ]:
from google.colab import files

files.download("Sales_Dataset_With_Missing_And_Duplicates.xlsx")

In [ ]:
!ls
#clenaed dataset

Sales_Dataset_With_Missing_And_Duplicates.xlsx	sample_data